"""Policy file schema. Encodes:
  - V0: stateless per-tool baseline (destination allow/block lists).
  - V1-V3 tier parameters (ngram size / coverage threshold / decode limits).
  - V4 window parameters (parsed even though V4 itself is a stretch stub).
  - Enforcement action per tier, and the approval timeout (Section 5D).
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Optional


class AblationTier(str, Enum):
    V0 = "v0"
    V1 = "v1"
    V2 = "v2"
    V3 = "v3"
    V4 = "v4"

    def at_least(self, other: "AblationTier") -> bool:
        order = [AblationTier.V0, AblationTier.V1, AblationTier.V2, AblationTier.V3, AblationTier.V4]
        return order.index(self) >= order.index(other)


class EnforcementAction(str, Enum):
    ASK_USER = "ask_user"
    BLOCK = "block"


@dataclass
class ToolCapability:
    allowed_paths: list[str] = field(default_factory=list)
    blocked_paths: list[str] = field(default_factory=list)
    allowed_domains: list[str] = field(default_factory=list)
    blocked_domains: list[str] = field(default_factory=list)


@dataclass
class ServerBinding:
    server_id: str
    tool_capabilities: dict[str, ToolCapability] = field(default_factory=dict)


@dataclass
class ApproxMatchingConfig:
    """Section 5B: N-gram size and coverage threshold, both configurable,
    plus a sweep range used by the Week 4/5 evaluation harness.

    ## Granularity threshold (min_effective_fragment_chars)

    Coverage-based matching has a hard, measurable floor: a fragment
    shorter than `ngram_size` contributes ZERO n-grams and can never be
    detected by V3/V4 on its own, no matter how low `coverage_threshold`
    is set. More precisely, a fragment of length L contributes
    `max(0, L - ngram_size + 1)` n-grams — so the number of n-grams grows
    slowly just above the floor.

    `min_effective_fragment_chars` formalizes the length at which a
    fragment carries ENOUGH n-grams to be a meaningfully detectable
    signal (as opposed to technically-nonzero-but-negligible), rather
    than leaving this as an unmanaged, empirically-discovered artifact.
    It's a security/utility tradeoff, not a hard correctness boundary:
    - Set it too low, and single-character or near-empty fragments
      "count" as signal, inflating false-positive risk from incidental
      short overlaps.
    - Set it too high, and legitimately splittable secrets (M3/M4-style
      attacks using small chunks) evade detection more easily.

    This project's own ablation study (see benchmarks/results/
    chunk_size_failure.md, generated by `benchmarks/harness.py::
    chunk_size_detection_breakdown`) empirically measured the boundary at
    exactly `ngram_size + 3` characters for the default `ngram_size=4`
    (i.e. min_effective_fragment_chars=7): chunks of 4-6 characters
    reliably failed to accumulate enough coverage to cross
    `coverage_threshold=0.6`, even across multiple accumulated calls
    (V4); chunks of 7+ characters reliably succeeded. See
    `min_effective_fragment_chars_for()` below for the formula this was
    derived from, and treat the exact "+3" constant as an empirical
    finding for THIS coverage_threshold, not a theorem — re-derive it if
    `coverage_threshold` changes materially.
    """
    ngram_size: int = 4
    coverage_threshold: float = 0.6
    sweep_thresholds: list[float] = field(
        default_factory=lambda: [0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
    )
    # Empirically-measured granularity floor (see class docstring). Not
    # enforced anywhere automatically — it's descriptive/documentary,
    # consumed by fixtures.py and the evaluation harness so the boundary
    # is a named, citable parameter instead of a bare "7" scattered
    # through generator code.
    min_effective_fragment_chars: int = 7

    def min_effective_fragment_chars_for(self, min_ngrams: int = 4) -> int:
        """Derivation the default above was calibrated from: a fragment
        needs at least `min_ngrams` n-grams to be a reliable signal
        (rather than 1-2 incidental n-grams), and a fragment of length L
        yields `L - ngram_size + 1` n-grams — so L = ngram_size +
        min_ngrams - 1. With the defaults (ngram_size=4, min_ngrams=4)
        this returns 7, matching the measured boundary."""
        return self.ngram_size + min_ngrams - 1


@dataclass
class DecodeLimits:
    """Section 5G: transformation-tier resource limits — closes the
    decoding-DoS gap from the earlier draft."""
    max_candidate_len_bytes: int = 8 * 1024
    max_candidates_per_payload: int = 256
    max_expansion_ratio: float = 4.0
    max_nesting_depth: int = 3


@dataclass
class CrossCallWindowConfig:
    """Section 5C: dual time+count bound, keyed per (session_id, destination).

    ``review_threshold`` is an OPTIONAL early-containment threshold.  It is
    deliberately separate from the hard provenance detection threshold: the
    latter remains the research detector's calibrated decision boundary,
    while the former can ask for human approval / fail closed before a
    fragmented flow has leaked enough cumulative evidence to become a hard
    match.  ``None`` preserves the v0.3 validated behaviour exactly.
    """
    window_seconds: int = 300
    window_max_calls: int = 50
    review_threshold: float | None = None


@dataclass
class EnforcementConfig:
    """Section 5D: what happens on a match, and the fail-closed timeout."""
    on_match: EnforcementAction = EnforcementAction.ASK_USER
    approval_timeout_seconds: int = 60


@dataclass
class PolicyFile:
    version: str
    active_tier: AblationTier = AblationTier.V1
    server_bindings: list[ServerBinding] = field(default_factory=list)
    approx_matching: ApproxMatchingConfig = field(default_factory=ApproxMatchingConfig)
    decode_limits: DecodeLimits = field(default_factory=DecodeLimits)
    cross_call_window: CrossCallWindowConfig = field(default_factory=CrossCallWindowConfig)
    enforcement: EnforcementConfig = field(default_factory=EnforcementConfig)

    def binding_for(self, server_id: str) -> Optional[ServerBinding]:
        return next((b for b in self.server_bindings if b.server_id == server_id), None)

    @staticmethod
    def load(path: Path) -> "PolicyFile":
        raw = json.loads(Path(path).read_text())
        return PolicyFile.from_dict(raw)

    @staticmethod
    def from_dict(raw: dict) -> "PolicyFile":
        bindings = [
            ServerBinding(
                server_id=b["server_id"],
                tool_capabilities={
                    name: ToolCapability(**cap) for name, cap in b.get("tool_capabilities", {}).items()
                },
            )
            for b in raw.get("server_bindings", [])
        ]
        return PolicyFile(
            version=raw["version"],
            active_tier=AblationTier(raw.get("active_tier", "v1")),
            server_bindings=bindings,
            approx_matching=ApproxMatchingConfig(**raw.get("approx_matching", {})),
            decode_limits=DecodeLimits(**raw.get("decode_limits", {})),
            cross_call_window=CrossCallWindowConfig(**raw.get("cross_call_window", {})),
            enforcement=EnforcementConfig(
                on_match=EnforcementAction(raw.get("enforcement", {}).get("on_match", "ask_user")),
                approval_timeout_seconds=raw.get("enforcement", {}).get("approval_timeout_seconds", 60),
            ),
        )
